// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answer_choices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnswerChoices = `-- name: CreateAnswerChoices :many
INSERT INTO answer_choices (question_id, label, body)
VALUES
    ($1, $2, $3),
    ($1, $4, $5),
    ($1, $6, $7),
    ($1, $8, $9)
RETURNING id, question_id, label, body
`

type CreateAnswerChoicesParams struct {
	QuestionID pgtype.UUID
	Label      string
	Body       string
	Label_2    string
	Body_2     string
	Label_3    string
	Body_3     string
	Label_4    string
	Body_4     string
}

func (q *Queries) CreateAnswerChoices(ctx context.Context, arg CreateAnswerChoicesParams) ([]AnswerChoice, error) {
	rows, err := q.db.Query(ctx, createAnswerChoices,
		arg.QuestionID,
		arg.Label,
		arg.Body,
		arg.Label_2,
		arg.Body_2,
		arg.Label_3,
		arg.Body_3,
		arg.Label_4,
		arg.Body_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnswerChoice
	for rows.Next() {
		var i AnswerChoice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Label,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
