// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempt_responses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttemptResponses = `-- name: CreateAttemptResponses :exec
WITH data AS (
    SELECT
        unnest($1::UUID[])    AS attempt_id,
        unnest($2::UUID[])    AS question_id,
        unnest($3::UUID[])    AS selected_choice_id,
        NULLIF(unnest($4::TEXT[]), '')    AS open_response,
        unnest($5::BOOLEAN[]) AS is_correct
)
INSERT INTO attempt_responses (
    attempt_id, question_id, selected_choice_id, open_response, is_correct
)
SELECT attempt_id, question_id, selected_choice_id, open_response, is_correct
FROM data
`

type CreateAttemptResponsesParams struct {
	Column1 []pgtype.UUID
	Column2 []pgtype.UUID
	Column3 []pgtype.UUID
	Column4 []string
	Column5 []bool
}

func (q *Queries) CreateAttemptResponses(ctx context.Context, arg CreateAttemptResponsesParams) error {
	_, err := q.db.Exec(ctx, createAttemptResponses,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}

const getAttemptResponsesByAttempt = `-- name: GetAttemptResponsesByAttempt :many
SELECT id, attempt_id, question_id, selected_choice_id, open_response, is_correct FROM attempt_responses WHERE attempt_id = $1
`

func (q *Queries) GetAttemptResponsesByAttempt(ctx context.Context, attemptID pgtype.UUID) ([]AttemptResponse, error) {
	rows, err := q.db.Query(ctx, getAttemptResponsesByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttemptResponse
	for rows.Next() {
		var i AttemptResponse
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.SelectedChoiceID,
			&i.OpenResponse,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
