// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriend = `-- name: CreateFriend :one
INSERT INTO friends(
    user1,
    user2
) VALUES($1, $2) RETURNING id, user1, user2, created_at
`

type CreateFriendParams struct {
	User1 pgtype.UUID
	User2 pgtype.UUID
}

func (q *Queries) CreateFriend(ctx context.Context, arg CreateFriendParams) (Friend, error) {
	row := q.db.QueryRow(ctx, createFriend, arg.User1, arg.User2)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.User1,
		&i.User2,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFriend = `-- name: DeleteFriend :exec
DELETE FROM friends WHERE id = $1
`

func (q *Queries) DeleteFriend(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriend, id)
	return err
}

const getFriendsByUser = `-- name: GetFriendsByUser :many
SELECT 
    users.id  AS friend_id,
    friends.id AS friendship_id,
    users.full_name, 
    friends.created_at 
FROM friends 
    JOIN users ON users.id = CASE 
        WHEN friends.user1 = $1 THEN friends.user2 
        ELSE friends.user1 
    END
WHERE friends.user1 = $1 OR friends.user2 = $1
`

type GetFriendsByUserRow struct {
	FriendID     pgtype.UUID
	FriendshipID pgtype.UUID
	FullName     string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetFriendsByUser(ctx context.Context, user1 pgtype.UUID) ([]GetFriendsByUserRow, error) {
	rows, err := q.db.Query(ctx, getFriendsByUser, user1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsByUserRow
	for rows.Next() {
		var i GetFriendsByUserRow
		if err := rows.Scan(
			&i.FriendID,
			&i.FriendshipID,
			&i.FullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
