// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendship_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendshipRequest = `-- name: CreateFriendshipRequest :one
INSERT INTO friendship_requests (
    to_id,
    from_id,
    message
) VALUES ($1, $2, $3)
RETURNING 
    id, 
    to_id, 
    from_id, 
    message, 
    created_at,
    (SELECT full_name FROM users WHERE users.id = friendship_requests.from_id) AS sender_full_name
`

type CreateFriendshipRequestParams struct {
	ToID    pgtype.UUID
	FromID  pgtype.UUID
	Message pgtype.Text
}

type CreateFriendshipRequestRow struct {
	ID             pgtype.UUID
	ToID           pgtype.UUID
	FromID         pgtype.UUID
	Message        pgtype.Text
	CreatedAt      pgtype.Timestamptz
	SenderFullName string
}

func (q *Queries) CreateFriendshipRequest(ctx context.Context, arg CreateFriendshipRequestParams) (CreateFriendshipRequestRow, error) {
	row := q.db.QueryRow(ctx, createFriendshipRequest, arg.ToID, arg.FromID, arg.Message)
	var i CreateFriendshipRequestRow
	err := row.Scan(
		&i.ID,
		&i.ToID,
		&i.FromID,
		&i.Message,
		&i.CreatedAt,
		&i.SenderFullName,
	)
	return i, err
}

const deleteFriendshipRequest = `-- name: DeleteFriendshipRequest :one
DELETE FROM friendship_requests WHERE id = $1 RETURNING id, to_id, from_id, created_at, message
`

func (q *Queries) DeleteFriendshipRequest(ctx context.Context, id pgtype.UUID) (FriendshipRequest, error) {
	row := q.db.QueryRow(ctx, deleteFriendshipRequest, id)
	var i FriendshipRequest
	err := row.Scan(
		&i.ID,
		&i.ToID,
		&i.FromID,
		&i.CreatedAt,
		&i.Message,
	)
	return i, err
}

const getFriendshipRequestsByUser = `-- name: GetFriendshipRequestsByUser :many
SELECT 
    users.full_name, 
    friendship_requests.id, friendship_requests.to_id, friendship_requests.from_id, friendship_requests.created_at, friendship_requests.message
FROM friendship_requests JOIN users ON friendship_requests.from_id = users.id WHERE to_id = $1
`

type GetFriendshipRequestsByUserRow struct {
	FullName  string
	ID        pgtype.UUID
	ToID      pgtype.UUID
	FromID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Message   pgtype.Text
}

func (q *Queries) GetFriendshipRequestsByUser(ctx context.Context, toID pgtype.UUID) ([]GetFriendshipRequestsByUserRow, error) {
	rows, err := q.db.Query(ctx, getFriendshipRequestsByUser, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendshipRequestsByUserRow
	for rows.Next() {
		var i GetFriendshipRequestsByUserRow
		if err := rows.Scan(
			&i.FullName,
			&i.ID,
			&i.ToID,
			&i.FromID,
			&i.CreatedAt,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
