// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Difficulty string

const (
	DifficultyEasy   Difficulty = "easy"
	DifficultyMedium Difficulty = "medium"
	DifficultyHard   Difficulty = "hard"
)

func (e *Difficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Difficulty(s)
	case string:
		*e = Difficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for Difficulty: %T", src)
	}
	return nil
}

type NullDifficulty struct {
	Difficulty Difficulty
	Valid      bool // Valid is true if Difficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.Difficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Difficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Difficulty), nil
}

type QuestionType string

const (
	QuestionTypeMultipleChoice QuestionType = "multiple_choice"
	QuestionTypeOpenResponse   QuestionType = "open_response"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType
	Valid        bool // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type AnswerChoice struct {
	ID         pgtype.UUID
	QuestionID pgtype.UUID
	Label      string
	Body       string
}

type AttemptResponse struct {
	ID               pgtype.UUID
	AttemptID        pgtype.UUID
	QuestionID       pgtype.UUID
	SelectedChoiceID pgtype.UUID
	OpenResponse     pgtype.Text
	IsCorrect        pgtype.Bool
}

type Module struct {
	ID         pgtype.UUID
	PracticeID pgtype.UUID
	Name       string
	OrderIndex int16
}

type ModuleQuestion struct {
	ModuleID   pgtype.UUID
	QuestionID pgtype.UUID
	Number     int16
}

type OpenAnswerKey struct {
	ID           pgtype.UUID
	QuestionID   pgtype.UUID
	ModelAnswer  pgtype.Text
	MatchPattern pgtype.Text
}

type Practice struct {
	ID        pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PracticeAttempt struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	PublishedPracticeID pgtype.UUID
	StartedAt           pgtype.Timestamptz
	SubmittedAt         pgtype.Timestamptz
	RwScore             int16
	MathScore           int16
}

type PublishedPractice struct {
	ID          pgtype.UUID
	PracticeID  pgtype.UUID
	PublishedAt pgtype.Timestamptz
	PublishedBy pgtype.UUID
	Data        []byte
}

type Question struct {
	ID              pgtype.UUID
	Type            QuestionType
	Paragraph       pgtype.Text
	Prompt          string
	ImagePath       pgtype.Text
	Skill           pgtype.Text
	Domain          pgtype.Text
	Difficulty      string
	Explanation     pgtype.Text
	CorrectChoiceID pgtype.UUID
}

type QuestionAttempt struct {
	ID             pgtype.UUID
	Response       string
	QuestionID     pgtype.UUID
	IsCorrect      bool
	UserID         pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	ElapsedSeconds int32
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	FullName     string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
