// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getModulesByPracticeID = `-- name: GetModulesByPracticeID :many
SELECT id, name, order_index FROM modules WHERE practice_id = $1 ORDER BY order_index
`

type GetModulesByPracticeIDRow struct {
	ID         pgtype.UUID
	Name       string
	OrderIndex int16
}

func (q *Queries) GetModulesByPracticeID(ctx context.Context, practiceID pgtype.UUID) ([]GetModulesByPracticeIDRow, error) {
	rows, err := q.db.Query(ctx, getModulesByPracticeID, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModulesByPracticeIDRow
	for rows.Next() {
		var i GetModulesByPracticeIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OrderIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
