// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: open_answers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOpenAnswerKey = `-- name: CreateOpenAnswerKey :one
INSERT INTO open_answer_keys(question_id, match_pattern, model_answer) VALUES($1, $2, $3)
RETURNING id, question_id, model_answer, match_pattern
`

type CreateOpenAnswerKeyParams struct {
	QuestionID   pgtype.UUID
	MatchPattern pgtype.Text
	ModelAnswer  pgtype.Text
}

func (q *Queries) CreateOpenAnswerKey(ctx context.Context, arg CreateOpenAnswerKeyParams) (OpenAnswerKey, error) {
	row := q.db.QueryRow(ctx, createOpenAnswerKey, arg.QuestionID, arg.MatchPattern, arg.ModelAnswer)
	var i OpenAnswerKey
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ModelAnswer,
		&i.MatchPattern,
	)
	return i, err
}
