// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: practice_attempt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPracticeAttempt = `-- name: CreatePracticeAttempt :one
INSERT INTO practice_attempts(
    user_id, 
    published_practice_id, 
    started_at, 
    submitted_at, 
    rw_score, 
    math_score) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, published_practice_id, started_at, submitted_at, rw_score, math_score
`

type CreatePracticeAttemptParams struct {
	UserID              pgtype.UUID
	PublishedPracticeID pgtype.UUID
	StartedAt           pgtype.Timestamptz
	SubmittedAt         pgtype.Timestamptz
	RwScore             int16
	MathScore           int16
}

func (q *Queries) CreatePracticeAttempt(ctx context.Context, arg CreatePracticeAttemptParams) (PracticeAttempt, error) {
	row := q.db.QueryRow(ctx, createPracticeAttempt,
		arg.UserID,
		arg.PublishedPracticeID,
		arg.StartedAt,
		arg.SubmittedAt,
		arg.RwScore,
		arg.MathScore,
	)
	var i PracticeAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublishedPracticeID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.RwScore,
		&i.MathScore,
	)
	return i, err
}

const getById = `-- name: GetById :one
SELECT id, user_id, published_practice_id, started_at, submitted_at, rw_score, math_score FROM practice_attempts WHERE id = $1
`

func (q *Queries) GetById(ctx context.Context, id pgtype.UUID) (PracticeAttempt, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i PracticeAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublishedPracticeID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.RwScore,
		&i.MathScore,
	)
	return i, err
}

const getPracticeAttemptsByUser = `-- name: GetPracticeAttemptsByUser :many
SELECT id, user_id, published_practice_id, started_at, submitted_at, rw_score, math_score FROM practice_attempts WHERE user_id = $1 ORDER BY submitted_at DESC
`

func (q *Queries) GetPracticeAttemptsByUser(ctx context.Context, userID pgtype.UUID) ([]PracticeAttempt, error) {
	rows, err := q.db.Query(ctx, getPracticeAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PracticeAttempt
	for rows.Next() {
		var i PracticeAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublishedPracticeID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.RwScore,
			&i.MathScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
