// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: practices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPracticeWithModules = `-- name: CreatePracticeWithModules :one
WITH new_practice AS (
    INSERT INTO practices (title)
    VALUES ($1)
    RETURNING id, title, created_at, updated_at
),
inserted_modules AS (
    INSERT INTO modules (practice_id, order_index, name)
    SELECT id, order_index, name
    FROM new_practice,
    (VALUES
        (1, 'Reading And Writing 1'),
        (2, 'Reading And Writing 2'),
        (3, 'Math 1'),
        (4, 'Math 2')
    ) AS t(order_index, name)
    RETURNING id

)
SELECT id, title, created_at, updated_at FROM new_practice
`

type CreatePracticeWithModulesRow struct {
	ID        pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePracticeWithModules(ctx context.Context, title string) (CreatePracticeWithModulesRow, error) {
	row := q.db.QueryRow(ctx, createPracticeWithModules, title)
	var i CreatePracticeWithModulesRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPracticePreviews = `-- name: GetPracticePreviews :many
SELECT id, title, created_at, updated_at FROM practices
`

func (q *Queries) GetPracticePreviews(ctx context.Context) ([]Practice, error) {
	rows, err := q.db.Query(ctx, getPracticePreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Practice
	for rows.Next() {
		var i Practice
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPracticeWithModules = `-- name: GetPracticeWithModules :many
SELECT
    p.id,
    p.title,
    p.created_at,
    p.updated_at,
    m.id AS module_id,
    m.name AS module_name,
    m.order_index
FROM practices p
JOIN modules m ON m.practice_id = p.id
WHERE p.id = $1
ORDER BY m.order_index
`

type GetPracticeWithModulesRow struct {
	ID         pgtype.UUID
	Title      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	ModuleID   pgtype.UUID
	ModuleName string
	OrderIndex int16
}

func (q *Queries) GetPracticeWithModules(ctx context.Context, id pgtype.UUID) ([]GetPracticeWithModulesRow, error) {
	rows, err := q.db.Query(ctx, getPracticeWithModules, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPracticeWithModulesRow
	for rows.Next() {
		var i GetPracticeWithModulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModuleID,
			&i.ModuleName,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
