// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: published_practices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublishedPractice = `-- name: GetPublishedPractice :one
SELECT id, practice_id, published_at, published_by, data FROM published_practices WHERE id = $1
`

func (q *Queries) GetPublishedPractice(ctx context.Context, id pgtype.UUID) (PublishedPractice, error) {
	row := q.db.QueryRow(ctx, getPublishedPractice, id)
	var i PublishedPractice
	err := row.Scan(
		&i.ID,
		&i.PracticeID,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.Data,
	)
	return i, err
}

const publishPractice = `-- name: PublishPractice :one
INSERT INTO published_practices(practice_id, published_by, data) VALUES(
    $1, $2, $3
) RETURNING id
`

type PublishPracticeParams struct {
	PracticeID  pgtype.UUID
	PublishedBy pgtype.UUID
	Data        []byte
}

func (q *Queries) PublishPractice(ctx context.Context, arg PublishPracticeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, publishPractice, arg.PracticeID, arg.PublishedBy, arg.Data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
