// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: published_practices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublishedPractice = `-- name: GetPublishedPractice :one
SELECT id, practice_id, published_at, published_by, data FROM published_practices WHERE id = $1
`

func (q *Queries) GetPublishedPractice(ctx context.Context, id pgtype.UUID) (PublishedPractice, error) {
	row := q.db.QueryRow(ctx, getPublishedPractice, id)
	var i PublishedPractice
	err := row.Scan(
		&i.ID,
		&i.PracticeID,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.Data,
	)
	return i, err
}

const getPublishedPracticesPreviews = `-- name: GetPublishedPracticesPreviews :many
SELECT p.title, pp.published_at, pp.id 
FROM 
published_practices pp 
JOIN 
practices p 
ON p.id = pp.practice_id
`

type GetPublishedPracticesPreviewsRow struct {
	Title       string
	PublishedAt pgtype.Timestamptz
	ID          pgtype.UUID
}

func (q *Queries) GetPublishedPracticesPreviews(ctx context.Context) ([]GetPublishedPracticesPreviewsRow, error) {
	rows, err := q.db.Query(ctx, getPublishedPracticesPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublishedPracticesPreviewsRow
	for rows.Next() {
		var i GetPublishedPracticesPreviewsRow
		if err := rows.Scan(&i.Title, &i.PublishedAt, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPractice = `-- name: PublishPractice :one
INSERT INTO published_practices(practice_id, published_by, data) VALUES(
    $1, $2, $3
) RETURNING id
`

type PublishPracticeParams struct {
	PracticeID  pgtype.UUID
	PublishedBy pgtype.UUID
	Data        []byte
}

func (q *Queries) PublishPractice(ctx context.Context, arg PublishPracticeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, publishPractice, arg.PracticeID, arg.PublishedBy, arg.Data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
