// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    type,
    paragraph,
    prompt,
    image_path,
    skill,
    domain,
    difficulty,
    explanation
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, type, paragraph, prompt, image_path, skill, domain, difficulty, explanation, correct_choice_id
`

type CreateQuestionParams struct {
	Type        QuestionType
	Paragraph   pgtype.Text
	Prompt      string
	ImagePath   pgtype.Text
	Skill       pgtype.Text
	Domain      pgtype.Text
	Difficulty  string
	Explanation pgtype.Text
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.Type,
		arg.Paragraph,
		arg.Prompt,
		arg.ImagePath,
		arg.Skill,
		arg.Domain,
		arg.Difficulty,
		arg.Explanation,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Paragraph,
		&i.Prompt,
		&i.ImagePath,
		&i.Skill,
		&i.Domain,
		&i.Difficulty,
		&i.Explanation,
		&i.CorrectChoiceID,
	)
	return i, err
}

const filterQuestions = `-- name: FilterQuestions :many
SELECT q.id
FROM questions q
LEFT JOIN LATERAL (
    SELECT is_correct
    FROM question_attempts
    WHERE question_id = q.id
      AND user_id = $1::uuid
    ORDER BY created_at DESC
    LIMIT 1
) qa ON true
WHERE 
    (difficulty = ANY($2::difficulty[]))
    AND (
        $3::text[] @> ARRAY['all']::text[]
        OR domain = ANY($3::text[])
    )
    AND (
        $4::text[] @> ARRAY['all']::text[] 
        OR skill = ANY($4::text[])
    )
    AND (
        $5::text = 'all'
        OR ($5::text = 'correct'     AND qa.is_correct = true)
        OR ($5::text = 'incorrect'   AND qa.is_correct = false)
        OR ($5::text = 'unattempted' AND qa.is_correct IS NULL)
    )
`

type FilterQuestionsParams struct {
	UserID           pgtype.UUID
	DifficultyLevels []string
	Domains          []string
	Skills           []string
	AttemptStatus    string
}

func (q *Queries) FilterQuestions(ctx context.Context, arg FilterQuestionsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, filterQuestions,
		arg.UserID,
		arg.DifficultyLevels,
		arg.Domains,
		arg.Skills,
		arg.AttemptStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT
    q.id,
    q.type,
    q.paragraph,
    q.prompt,
    q.image_path,
    q.skill,
    q.domain,
    q.difficulty,
    q.explanation,
    q.correct_choice_id,
    json_agg(
        json_build_object(
            'id',    ac.id,
            'label', ac.label,
            'body',  ac.body
        )
    ) FILTER (WHERE ac.id IS NOT NULL)
    AS choices,
    oak.id            AS answer_key_id,
    oak.model_answer  AS answer_key_model_answer,
    oak.match_pattern AS answer_key_match_pattern
FROM questions q
LEFT JOIN answer_choices ac  ON ac.question_id = q.id
LEFT JOIN open_answer_keys oak ON oak.question_id = q.id
WHERE q.id = $1
GROUP BY q.id, oak.id
`

type GetQuestionByIDRow struct {
	ID                    pgtype.UUID
	Type                  QuestionType
	Paragraph             pgtype.Text
	Prompt                string
	ImagePath             pgtype.Text
	Skill                 pgtype.Text
	Domain                pgtype.Text
	Difficulty            string
	Explanation           pgtype.Text
	CorrectChoiceID       pgtype.UUID
	Choices               []byte
	AnswerKeyID           pgtype.UUID
	AnswerKeyModelAnswer  pgtype.Text
	AnswerKeyMatchPattern pgtype.Text
}

func (q *Queries) GetQuestionByID(ctx context.Context, id pgtype.UUID) (GetQuestionByIDRow, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i GetQuestionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Paragraph,
		&i.Prompt,
		&i.ImagePath,
		&i.Skill,
		&i.Domain,
		&i.Difficulty,
		&i.Explanation,
		&i.CorrectChoiceID,
		&i.Choices,
		&i.AnswerKeyID,
		&i.AnswerKeyModelAnswer,
		&i.AnswerKeyMatchPattern,
	)
	return i, err
}

const getQuestionDistribution = `-- name: GetQuestionDistribution :many
WITH latest_attempts AS (
    SELECT DISTINCT ON (question_id)
        question_id,
        is_correct
    FROM question_attempts
    WHERE user_id = $1
    ORDER BY question_id, created_at DESC  -- adjust column name if needed
)
SELECT 
    q.domain, 
    q.skill,
    q.difficulty,
    COUNT(q.id)                                                              AS total_count,
    COUNT(la.question_id) FILTER (WHERE la.is_correct = true)               AS correct_count,
    COUNT(la.question_id) FILTER (WHERE la.is_correct = false)              AS incorrect_count,
    COUNT(q.id) FILTER (WHERE la.question_id IS NULL)                       AS unattempted_count
FROM questions q
LEFT JOIN latest_attempts la ON la.question_id = q.id
WHERE q.skill <> 'imported' 
GROUP BY q.domain, q.skill, q.difficulty
`

type GetQuestionDistributionRow struct {
	Domain           pgtype.Text
	Skill            pgtype.Text
	Difficulty       string
	TotalCount       int64
	CorrectCount     int64
	IncorrectCount   int64
	UnattemptedCount int64
}

func (q *Queries) GetQuestionDistribution(ctx context.Context, userID pgtype.UUID) ([]GetQuestionDistributionRow, error) {
	rows, err := q.db.Query(ctx, getQuestionDistribution, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionDistributionRow
	for rows.Next() {
		var i GetQuestionDistributionRow
		if err := rows.Scan(
			&i.Domain,
			&i.Skill,
			&i.Difficulty,
			&i.TotalCount,
			&i.CorrectCount,
			&i.IncorrectCount,
			&i.UnattemptedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByModule = `-- name: GetQuestionsByModule :many
SELECT
    q.id,
    q.type,
    q.paragraph,
    q.prompt,
    q.image_path,
    q.correct_choice_id,
    q.difficulty,
    q.domain,
    q.skill,
    q.explanation,
    mq.number,

    (SELECT json_agg(ch ORDER BY ch.label) 
        FROM (
            SELECT id, label, body 
            FROM answer_choices 
            WHERE question_id = q.id
        ) ch
    ) 
    AS choices,

    (SELECT json_build_object(
        'id', oak.id,
        'model_answer', oak.model_answer,
        'match_pattern', oak.match_pattern
     ) 
     FROM open_answer_keys oak 
     WHERE oak.question_id = q.id
    ) AS open_key
FROM questions q
JOIN module_questions mq ON q.id = mq.question_id
WHERE mq.module_id = $1
ORDER BY mq.number
`

type GetQuestionsByModuleRow struct {
	ID              pgtype.UUID
	Type            QuestionType
	Paragraph       pgtype.Text
	Prompt          string
	ImagePath       pgtype.Text
	CorrectChoiceID pgtype.UUID
	Difficulty      string
	Domain          pgtype.Text
	Skill           pgtype.Text
	Explanation     pgtype.Text
	Number          int16
	Choices         []byte
	OpenKey         []byte
}

func (q *Queries) GetQuestionsByModule(ctx context.Context, moduleID pgtype.UUID) ([]GetQuestionsByModuleRow, error) {
	rows, err := q.db.Query(ctx, getQuestionsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsByModuleRow
	for rows.Next() {
		var i GetQuestionsByModuleRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Paragraph,
			&i.Prompt,
			&i.ImagePath,
			&i.CorrectChoiceID,
			&i.Difficulty,
			&i.Domain,
			&i.Skill,
			&i.Explanation,
			&i.Number,
			&i.Choices,
			&i.OpenKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkQuestionToModule = `-- name: LinkQuestionToModule :exec
INSERT INTO module_questions (
    module_id,
    question_id,
    number
)  VALUES($1, $2, $3)
`

type LinkQuestionToModuleParams struct {
	ModuleID   pgtype.UUID
	QuestionID pgtype.UUID
	Number     int16
}

func (q *Queries) LinkQuestionToModule(ctx context.Context, arg LinkQuestionToModuleParams) error {
	_, err := q.db.Exec(ctx, linkQuestionToModule, arg.ModuleID, arg.QuestionID, arg.Number)
	return err
}

const setCorrectChoice = `-- name: SetCorrectChoice :exec
UPDATE questions
SET correct_choice_id = $1
WHERE id = $2
`

type SetCorrectChoiceParams struct {
	CorrectChoiceID pgtype.UUID
	ID              pgtype.UUID
}

func (q *Queries) SetCorrectChoice(ctx context.Context, arg SetCorrectChoiceParams) error {
	_, err := q.db.Exec(ctx, setCorrectChoice, arg.CorrectChoiceID, arg.ID)
	return err
}
