// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestionAttempt = `-- name: CreateQuestionAttempt :one
INSERT INTO question_attempts(response, elapsed_seconds ,question_id, user_id, is_correct) VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, response, question_id, is_correct, user_id, created_at, elapsed_seconds
`

type CreateQuestionAttemptParams struct {
	Response       string
	ElapsedSeconds int32
	QuestionID     pgtype.UUID
	UserID         pgtype.UUID
	IsCorrect      bool
}

func (q *Queries) CreateQuestionAttempt(ctx context.Context, arg CreateQuestionAttemptParams) (QuestionAttempt, error) {
	row := q.db.QueryRow(ctx, createQuestionAttempt,
		arg.Response,
		arg.ElapsedSeconds,
		arg.QuestionID,
		arg.UserID,
		arg.IsCorrect,
	)
	var i QuestionAttempt
	err := row.Scan(
		&i.ID,
		&i.Response,
		&i.QuestionID,
		&i.IsCorrect,
		&i.UserID,
		&i.CreatedAt,
		&i.ElapsedSeconds,
	)
	return i, err
}

const getQuestionAttemptsByUser = `-- name: GetQuestionAttemptsByUser :many
SELECT id, response, question_id, is_correct, user_id, created_at, elapsed_seconds FROM question_attempts WHERE user_id = $1
`

func (q *Queries) GetQuestionAttemptsByUser(ctx context.Context, userID pgtype.UUID) ([]QuestionAttempt, error) {
	rows, err := q.db.Query(ctx, getQuestionAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionAttempt
	for rows.Next() {
		var i QuestionAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Response,
			&i.QuestionID,
			&i.IsCorrect,
			&i.UserID,
			&i.CreatedAt,
			&i.ElapsedSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
